### ISSUE TITLE
Some suggestions to improve your score

### ISSUE THREAD

**Issue by John1231983** [milani/science-bowl-2018#1]
Hi, thanks for your code. I checked your current score about 0.36 LB. It is too low than standard implementation of mask rcnn ( I got 0.41). I would like to suggest you some schemes:
1. Randomly crop training image into some fixed size such as 128x128 then train on the size. Don't add the zero padding to a larger size such as 1024x1024, it may lost the image distribution. In the inference, you can split the testing image into sub-images of 128x128 and combine together to make final result (I did not complete the combination step)
2. Set larger RPN_TRAIN_ANCHORS_PER_IMAGE  such as 512
3. Use smaller network such as resnet-50 instead of resnet-101
4. Augmentation data as you did

This is my setting to achieve above score
```
IMAGES_PER_GPU = 2 
GPU_COUNT = 1
NUM_CLASSES = 1 + 1 # Background + Nuclei 
USE_MINI_MASK=True 
MINI_MASK_SHAPE = (56,56) 
RPN_ANCHOR_SCALES = (8, 16, 32, 64,128) 
RPN_ANCHOR_RATIOS = [0.25, 0.5, 1, 2, 4] 
RPN_NMS_THRESHOLD = 0.7 
IMAGE_CROP_WIDTH=128
IMAGE_CROP_HEIGHT=128
DETECTION_MAX_INSTANCES = 200 
RPN_TRAIN_ANCHORS_PER_IMAGE = 512
RPN_NMS_THRESHOLD = 0.6 
MAX_GT_INSTANCES = 200 
DETECTION_MIN_CONFIDENCE = 0.6
```

**Comment by milani** [comment]
Thanks John. Actually my score is with Mask RCNN. This code is still missing a mask head. 

I am new to image segmentation so I tried to implement one from scratch to learn more. Lets see if I can beat my own score;)

**Comment by John1231983** [comment]
I see. Do you have LB score for the repo?

**Comment by milani** [comment]
No I did not submit it.
